language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

install: true

git:
  depth: 1

notifications:
  email: false

script:
  - go test  -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)